### PR TITLE
Enable Live Tracing of EventSource Events

### PR DESCRIPTION
**Pull request by brianrob**
Running ./perfcollect livetrace will dump EventSource events to the console as they are emitted.

### CODE REVIEW

**Comment by brianrob** [comment]
@stephentoub PTAL.

Note that you'll need to set COMPlus_EnableEventLog=1 before the runtime starts so that it emits events to LTTng.

**Comment by stephentoub** [comment]
Thanks!

**Comment by stephentoub** [comment]
LGTM.  Looking forward to trying it.

**Comment by brianrob** [comment]
Thanks much!

**Pull request merged**
